import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideMenu from "./components/sideMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IT Step Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col md:flex-row min-h-screen">
          <aside className="w-full md:w-64 md:min-h-screen bg-gray-100">
            <SideMenu />
          </aside>
          <main className="flex-1 text-white">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
